### PR TITLE
Modified Team Section

### PR DESCRIPTION
**Pull request by aayushpathak11**
<hr>

## Description 📜

- Modified DevsActivity to make Team section completely dynamic using Retrofit.
- On clicking a particular tile user will be redirected to his/her github page.
- If the name is not available then username will be used in particular tile.
- Used Lottie Animation for better user experience.
- Added Shimmer effect to fill up the time when recycler view is loading. 
Fixes # 27 

<hr>

## Domain of Contribution 📊

- [ ] Documentation
- [x] Android (Kotlin)
- [ ] Backend (Express)

<hr>

## Checklist ✅

- [x] I follow [Code of Conduct](https://github.com/vigneshshettyin/Meetly/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor

<hr>

## Screenshots / Gif 📸

<hr>

### CODE REVIEW

**Comment by aayushpathak11** [comment]
Hello @vigneshshettyin 
Could you please review the PR and let me know any suggestions/changes.

**Review by vigneshshettyin — APPROVED** [review]

**Comment by vigneshshettyin** [comment]
Hey, @aayushpathak11 thanks for contributing!

**Comment by vigneshshettyin** [comment]
Hey, @aayushpathak11 if you are interested you can raise issue to add shimmerframelayout for mainactivity, supportactivity etc..

**Comment by aayushpathak11** [comment]
@vigneshshettyin yes sir I am interested.
Can you please explain more like where they need shimmer layout.

**Comment by aayushpathak11** [comment]
Also sir @vigneshshettyin 
I would be more than excited to work upon new features in the app (as currently i am not very well versed with codebase so i am not able to come up with what new can be added) so if you have anything which you think can be added or changed please share , would like to contribute to the best of my efforts.

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin yes sir I am interested. Can you please explain more like where they need shimmer layout.

In mainactivity file there is a recycle view which is used to list all the meetings of user. Also, in the supportactivity there is recycle view which quires the support updates from fire store. @aayushpathak11

**Pull request merged**
