### PR TITLE
Hide keyboard in auth

### LINKED ISSUE #18: [Feature Request]: Hiding of keyboard after pressing Login Button, Register Button, and Reset Password Button in Auth section
### Description

Description

After filling the fields in the auth section, we must hide the keyboard for a better user experience. In case, if the user does not closes the keyboard manually, he/she will not able to see the snackbar in case of any error.

### Domain

Android (Kotlin)

### Code of Conduct

- [X] I follow [Code of Conduct](https://github.com/vigneshshettyin/Meetly/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by its-me-debk007**
<hr>

## Description 📜

Hiding of keyboard in Auth after pressing the button..
Fixes #18 

<hr>

## Domain of Contribution 📊

- [ ] Documentation
- [x] Android (Kotlin)
- [ ] Backend (Express)

<hr>

## Checklist ✅

- [x] I follow [Code of Conduct](https://github.com/vigneshshettyin/Meetly/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor

<hr>

## Screenshots / Gif 📸

<hr>

### CODE REVIEW

**Comment by vigneshshettyin** [comment]
> Screenshots / Gif 📸

Thanks for raising the pr. Please attach screenshots or screen recordings showing the changes done for better transparency. @its-me-debk007

**Review by vigneshshettyin — APPROVED** [review]

**Review by vigneshshettyin — APPROVED** [review]

**Comment by its-me-debk007** [comment]
Thank u @vigneshshettyin Sir

**Comment by vigneshshettyin** [comment]
> Thank u @vigneshshettyin Sir

Hi, @its-me-debk007 Please attach screenshots or screen recordings showing the changes done for better transparency. After which I can merge your pr.

**Comment by its-me-debk007** [comment]
Sir, here is the screen recorded video

https://user-images.githubusercontent.com/81604986/156914729-7cd28d87-da01-4f14-8fd1-762b9074a4c0.mp4

**Comment by vigneshshettyin** [comment]
Thanks for contributing @its-me-debk007

**Pull request merged**
