### PR TITLE
[fix]: Update README.md

### PR DESCRIPTION
**Pull request by YASH-YADAV-dynamo**
Added commands in README.md for steps to set the environment for contribution

<hr>

## Description 📜

Fixed README.md with steps for user to just copy-paste in terminal to setup the environment.
Fixes  <#45> 

<hr>

## Domain of Contribution 📊

- [x] Documentation
- [x] Android (Kotlin)

<hr>

## Checklist ✅

- [x] I follow [Code of Conduct](https://github.com/vigneshshettyin/Meetly/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have put headings in my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.

<hr>

<hr>

### CODE REVIEW

**Review by vigneshshettyin — CHANGES_REQUESTED** [review]
This is not enough. create a separate file with complete guide to setup project locally as well @YASH-YADAV-dynamo

**Comment by YASH-YADAV-dynamo** [comment]
Ok,sure will update it.

**Comment by YASH-YADAV-dynamo** [comment]
Created a separate file as "contribution.md" for steps to contribute and for setting up the project locally mentioned to install android studio

**Comment by YASH-YADAV-dynamo** [comment]
If any more changes are needed ,please mention them in detail..i will surely work on them

**Pull request merged**
